# -*- coding: utf-8 -*-
"""Mpig.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxLQGmK_sQRqlGVJluE_cpq3w6o2x-k3
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score, RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mean_squared_error, r2_score, accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# For Google Colab, mount Google Drive (optional - for saving models)
from google.colab import drive
drive.mount('/content/drive')

# Load the data
df = pd.read_csv('climate_data_Mpigi (1).csv')

# Display basic information
print("Dataset Shape:", df.shape)
print("\nFirst 5 rows:")
print(df.head())
print("\nDataset Info:")
print(df.info())
print("\nStatistical Summary:")
print(df.describe())

# Check for missing values
print("\nMissing Values:")
print(df.isnull().sum())

# Create flood risk categories based on precipitation
# High precipitation = higher flood risk

# Method 1: Create binary classification (Flood / No Flood)
# Define threshold for flood risk (e.g., precipitation above 150mm)
df['Flood_Risk_Binary'] = (df['Precipitation'] > 150).astype(int)

# Method 2: Create multi-class flood risk (Low, Medium, High)
def categorize_flood_risk(precip):
    if precip < 80:
        return 0  # Low Risk
    elif precip < 150:
        return 1  # Medium Risk
    else:
        return 2  # High Risk

df['Flood_Risk_Category'] = df['Precipitation'].apply(categorize_flood_risk)

# Check distribution
print("\nFlood Risk Distribution (Binary):")
print(df['Flood_Risk_Binary'].value_counts())
print("\nFlood Risk Distribution (Multi-class):")
print(df['Flood_Risk_Category'].value_counts())

# Visualize relationships
fig, axes = plt.subplots(2, 3, figsize=(15, 10))

# Precipitation by month
monthly_precip = df.groupby('Month')['Precipitation'].mean()
axes[0, 0].bar(monthly_precip.index, monthly_precip.values)
axes[0, 0].set_title('Average Precipitation by Month')
axes[0, 0].set_xlabel('Month')
axes[0, 0].set_ylabel('Precipitation (mm)')

# Precipitation by season
seasonal_precip = df.groupby('Season')['Precipitation'].mean()
axes[0, 1].bar(seasonal_precip.index, seasonal_precip.values)
axes[0, 1].set_title('Average Precipitation by Season')
axes[0, 1].set_xlabel('Season')
axes[0, 1].set_ylabel('Precipitation (mm)')

# Temperature trends
axes[0, 2].plot(df.groupby('Year')['Tmean'].mean(), marker='o')
axes[0, 2].set_title('Mean Temperature Trend Over Years')
axes[0, 2].set_xlabel('Year')
axes[0, 2].set_ylabel('Temperature (°C)')

# Precipitation over years
axes[1, 0].plot(df.groupby('Year')['Precipitation'].sum(), marker='o', color='red')
axes[1, 0].set_title('Total Annual Precipitation')
axes[1, 0].set_xlabel('Year')
axes[1, 0].set_ylabel('Precipitation (mm)')

# Correlation heatmap
numeric_cols = df.select_dtypes(include=[np.number]).columns
correlation = df[numeric_cols].corr()
sns.heatmap(correlation, annot=True, fmt='.2f', ax=axes[1, 1], cmap='coolwarm')
axes[1, 1].set_title('Correlation Matrix')

# Distribution of precipitation
axes[1, 2].hist(df['Precipitation'], bins=30, edgecolor='black', alpha=0.7)
axes[1, 2].axvline(x=150, color='red', linestyle='--', label='Flood Threshold')
axes[1, 2].set_title('Distribution of Precipitation')
axes[1, 2].set_xlabel('Precipitation (mm)')
axes[1, 2].set_ylabel('Frequency')
axes[1, 2].legend()

plt.tight_layout()
plt.show()

# Create additional features that might help predict floods

# Lag features (previous months' precipitation)
df = df.sort_values(['Year', 'Month'])
df['Prev_Month_Precip'] = df.groupby('Year')['Precipitation'].shift(1)

# Rolling averages (3-month and 6-month)
df['Precip_3mo_avg'] = df.groupby('Year')['Precipitation'].transform(lambda x: x.rolling(3, min_periods=1).mean())
df['Precip_6mo_avg'] = df.groupby('Year')['Precipitation'].transform(lambda x: x.rolling(6, min_periods=1).mean())

# Temperature range
df['Temp_Range'] = df['Tmax'] - df['Tmin']

# Seasonal indicators (one-hot encoding)
season_dummies = pd.get_dummies(df['Season'], prefix='Season')
df = pd.concat([df, season_dummies], axis=1)

# Month as cyclical feature (to capture seasonal patterns)
df['Month_Sin'] = np.sin(2 * np.pi * df['Month']/12)
df['Month_Cos'] = np.cos(2 * np.pi * df['Month']/12)

# Fill NaN values from lag features
df = df.fillna(method='bfill').fillna(method='ffill')

print("Features after engineering:")
print(df.head())

# Define features and target
# For binary classification
feature_columns = ['Year', 'Month', 'Tmin', 'Tmax', 'Tmean',
                   'Prev_Month_Precip', 'Precip_3mo_avg', 'Precip_6mo_avg',
                   'Temp_Range', 'Month_Sin', 'Month_Cos',
                   'Season_Autumn', 'Season_Spring', 'Season_Summer', 'Season_Winter']

# Remove any rows with NaN values
df_clean = df.dropna()

X = df_clean[feature_columns]
y_binary = df_clean['Flood_Risk_Binary']
y_multiclass = df_clean['Flood_Risk_Category']

# Split the data
X_train, X_test, y_train_binary, y_test_binary = train_test_split(
    X, y_binary, test_size=0.2, random_state=42, stratify=y_binary
)

X_train_mc, X_test_mc, y_train_mc, y_test_mc = train_test_split(
    X, y_multiclass, test_size=0.2, random_state=42, stratify=y_multiclass
)

print(f"Training set size: {X_train.shape}")
print(f"Test set size: {X_test.shape}")
print("\nTarget distribution in training set (Binary):")
print(y_train_binary.value_counts(normalize=True))

# Random Forest doesn't require scaling, but we'll do it for completeness
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_mc_scaled = scaler.fit_transform(X_train_mc)
X_test_mc_scaled = scaler.transform(X_test_mc)

# Initialize and train Random Forest for binary classification
rf_binary = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_binary.fit(X_train_scaled, y_train_binary)

# Make predictions
y_pred_binary = rf_binary.predict(X_test_scaled)
y_pred_proba_binary = rf_binary.predict_proba(X_test_scaled)

# Evaluate the model
accuracy = accuracy_score(y_test_binary, y_pred_binary)
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test_binary, y_pred_binary,
                          target_names=['No Flood', 'Flood']))

# Confusion Matrix
cm = confusion_matrix(y_test_binary, y_pred_binary)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['No Flood', 'Flood'],
            yticklabels=['No Flood', 'Flood'])
plt.title('Confusion Matrix - Flood Prediction')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Initialize and train Random Forest for multi-class classification
rf_multiclass = RandomForestClassifier(
    n_estimators=100,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

# Train the model
rf_multiclass.fit(X_train_mc_scaled, y_train_mc)

# Make predictions
y_pred_mc = rf_multiclass.predict(X_test_mc_scaled)
y_pred_proba_mc = rf_multiclass.predict_proba(X_test_mc_scaled)

# Evaluate the model
accuracy_mc = accuracy_score(y_test_mc, y_pred_mc)
print(f"Accuracy (Multi-class): {accuracy_mc:.4f}")
print("\nClassification Report:")
print(classification_report(y_test_mc, y_pred_mc,
                          target_names=['Low Risk', 'Medium Risk', 'High Risk']))

# Confusion Matrix
cm_mc = confusion_matrix(y_test_mc, y_pred_mc)
plt.figure(figsize=(10, 8))
sns.heatmap(cm_mc, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Low Risk', 'Medium Risk', 'High Risk'],
            yticklabels=['Low Risk', 'Medium Risk', 'High Risk'])
plt.title('Confusion Matrix - Flood Risk Categories')
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.show()

# Feature importance for binary model
feature_importance = pd.DataFrame({
    'feature': feature_columns,
    'importance': rf_binary.feature_importances_
}).sort_values('importance', ascending=False)

plt.figure(figsize=(10, 6))
plt.barh(feature_importance['feature'][:10], feature_importance['importance'][:10])
plt.xlabel('Importance')
plt.title('Top 10 Feature Importance - Flood Prediction')
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

print("\nTop 10 Most Important Features:")
print(feature_importance.head(10))

# Define parameter grid
param_grid = {
    'n_estimators': [50, 100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']
}

# Initialize RandomizedSearchCV
rf_random = RandomizedSearchCV(
    RandomForestClassifier(random_state=42),
    param_distributions=param_grid,
    n_iter=20,
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1,
    scoring='accuracy'
)

# Fit random search
print("Training with hyperparameter tuning...")
rf_random.fit(X_train_scaled, y_train_binary)

print("\nBest Parameters:")
print(rf_random.best_params_)
print(f"Best Cross-validation Score: {rf_random.best_score_:.4f}")

# Evaluate best model
best_rf = rf_random.best_estimator_
y_pred_best = best_rf.predict(X_test_scaled)
accuracy_best = accuracy_score(y_test_binary, y_pred_best)
print(f"Test Accuracy with Best Model: {accuracy_best:.4f}")

# Perform cross-validation
cv_scores = cross_val_score(best_rf, X_train_scaled, y_train_binary, cv=5, scoring='accuracy')
print(f"Cross-validation scores: {cv_scores}")
print(f"Mean CV score: {cv_scores.mean():.4f} (+/- {cv_scores.std() * 2:.4f})")

import joblib

# Save the model to Google Drive
model_path = '/content/drive/MyDrive/flood_prediction_model.pkl'
scaler_path = '/content/drive/MyDrive/flood_scaler.pkl'

joblib.dump(best_rf, model_path)
joblib.dump(scaler, scaler_path)

print(f"Model saved to: {model_path}")
print(f"Scaler saved to: {scaler_path}")

# Download the model locally (alternative)
from google.colab import files
joblib.dump(best_rf, 'flood_prediction_model.pkl')
files.download('flood_prediction_model.pkl')

def predict_flood_risk(year, month, tmin, tmax, tmean, precip, season, model, scaler, feature_cols):
    """
    Function to predict flood risk for new data
    """
    # Create a DataFrame with the input data
    new_data = pd.DataFrame({
        'Year': [year],
        'Month': [month],
        'Tmin': [tmin],
        'Tmax': [tmax],
        'Tmean': [tmean],
        'Precipitation': [precip]
    })

    # Add season dummy variables
    for s in ['Autumn', 'Spring', 'Summer', 'Winter']:
        new_data[f'Season_{s}'] = 1 if season == s else 0

    # Add engineered features
    new_data['Prev_Month_Precip'] = precip  # Simplified - in practice, you'd need historical data
    new_data['Precip_3mo_avg'] = precip
    new_data['Precip_6mo_avg'] = precip
    new_data['Temp_Range'] = tmax - tmin
    new_data['Month_Sin'] = np.sin(2 * np.pi * month/12)
    new_data['Month_Cos'] = np.cos(2 * np.pi * month/12)

    # Ensure columns are in the same order as training data
    new_data = new_data[feature_cols]

    # Scale the data
    new_data_scaled = scaler.transform(new_data)

    # Make prediction
    prediction = model.predict(new_data_scaled)[0]
    probability = model.predict_proba(new_data_scaled)[0]

    risk_levels = ['No Flood', 'Flood']

    return {
        'prediction': risk_levels[prediction],
        'probability_no_flood': probability[0],
        'probability_flood': probability[1]
    }

# Test the function with sample data
test_prediction = predict_flood_risk(
    year=2025,
    month=4,
    tmin=18.0,
    tmax=27.0,
    tmean=22.5,
    precip=200.0,
    season='Spring',
    model=best_rf,
    scaler=scaler,
    feature_cols=feature_columns
)

print("Sample Prediction:")
print(test_prediction)

# Create a comprehensive summary visualization
fig, axes = plt.subplots(2, 2, figsize=(15, 12))

# 1. Model Performance Comparison
models = ['Random Forest (Binary)', 'Random Forest (Multi)', 'Tuned RF']
accuracies = [accuracy, accuracy_mc, accuracy_best]
colors = ['skyblue', 'lightgreen', 'coral']
axes[0, 0].bar(models, accuracies, color=colors)
axes[0, 0].set_ylabel('Accuracy')
axes[0, 0].set_title('Model Performance Comparison')
axes[0, 0].set_ylim([0, 1])
for i, v in enumerate(accuracies):
    axes[0, 0].text(i, v + 0.01, f'{v:.3f}', ha='center')

# 2. Feature Importance
top_features = feature_importance.head(8)
axes[0, 1].barh(top_features['feature'], top_features['importance'], color='teal')
axes[0, 1].set_xlabel('Importance')
axes[0, 1].set_title('Top 8 Feature Importance')
axes[0, 1].invert_yaxis()

# 3. Prediction Distribution
axes[1, 0].hist(y_pred_proba_binary[:, 1], bins=20, edgecolor='black', alpha=0.7)
axes[1, 0].axvline(x=0.5, color='red', linestyle='--', label='Threshold')
axes[1, 0].set_xlabel('Flood Probability')
axes[1, 0].set_ylabel('Frequency')
axes[1, 0].set_title('Distribution of Flood Probabilities')
axes[1, 0].legend()

# 4. Actual vs Predicted (sample)
sample_size = min(50, len(y_test_binary))
sample_indices = np.random.choice(len(y_test_binary), sample_size, replace=False)
axes[1, 1].scatter(range(sample_size), y_test_binary.iloc[sample_indices],
                   label='Actual', alpha=0.6, marker='o')
axes[1, 1].scatter(range(sample_size), y_pred_binary[sample_indices],
                   label='Predicted', alpha=0.6, marker='x')
axes[1, 1].set_xlabel('Sample Index')
axes[1, 1].set_ylabel('Flood Risk (0=No, 1=Yes)')
axes[1, 1].set_title('Actual vs Predicted (Sample)')
axes[1, 1].legend()
axes[1, 1].set_yticks([0, 1])

plt.tight_layout()
plt.show()